version: 2
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run: 
          name: Install Sauce Connect
          command: |
            wget https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz
            tar -xzf sc-latest-linux.tar.gz
      - run: 
          name: sauce testing
          command: tar -xzf sc-4.4.12-linux.tar.gz
          environment:
            SAUCE_USERNAME: # Refer to circleci.com/docs/2.0/env-vars documentation for info
            SAUCE_ACCESS_KEY: # about setting up environment variables for auth secrets
      - run: # Wait for app to be ready
          command: wget --retry-connrefused --no-check-certificate -T 30 http://localhost:5000
      - run: # Run selenium tests
          command: nosetests
      - run: # wait for Sauce Connect to close the tunnel
          command: killall --wait sc 

